// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class CalculadoraImple_Stub
    extends java.rmi.server.RemoteStub
    implements Calculadora, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_calc_0;
    
    static {
	try {
	    $method_calc_0 = Calculadora.class.getMethod("calc", new java.lang.Class[] {double.class, double.class, char.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public CalculadoraImple_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of calc(double, double, char)
    public double calc(double $param_double_1, double $param_double_2, char $param_char_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_calc_0, new java.lang.Object[] {new java.lang.Double($param_double_1), new java.lang.Double($param_double_2), new java.lang.Character($param_char_3)}, -4877995276532483589L);
	    return ((java.lang.Double) $result).doubleValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
